<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class BmecWorldeTermsSeeder extends Seeder
{
    public function run()
    {
        $timestamp = Carbon::now();
        $data = [
            ['term' => 'laser', 'hints' => 'Bright beam in action.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'probe', 'hints' => 'Explorer of hidden realms.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'graft', 'hints' => 'A subtle merging technique.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'cells', 'hints' => 'Tiny building blocks.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'organ', 'hints' => 'An internal masterpiece.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'spine', 'hints' => 'Central structural support.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'nerve', 'hints' => 'Signal highway within.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'veins', 'hints' => 'Pathways for life’s flow.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'bones', 'hints' => 'Hard framework of life.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'aorta', 'hints' => 'Main conduit of life force.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'renal', 'hints' => 'Linked to kidney functions.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'ultra', 'hints' => 'Beyond the usual scope.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'heart', 'hints' => 'Rhythm of existence.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'morph', 'hints' => 'Shape-shifting transformation.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'tubes', 'hints' => 'Hollow channels in design.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'patch', 'hints' => 'Quick fix in structure.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'fluid', 'hints' => 'Flowing essential substance.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'cable', 'hints' => 'Flexible line for transfer.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'motor', 'hints' => 'Drives movement quietly.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'servo', 'hints' => 'Precision mover at work.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'brain', 'hints' => 'Central command center.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'vital', 'hints' => 'Crucial for existence.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'pulse', 'hints' => 'Rhythmic beat of life.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'prism', 'hints' => 'Splits the unseen spectrum.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'optic', 'hints' => 'Window to perception.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'scans', 'hints' => 'Detailed sweep of data.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'micro', 'hints' => 'Small scale complexity.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'stent', 'hints' => 'Support to open pathways.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'screw', 'hints' => 'Twisted fastener mechanism.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'nails', 'hints' => 'Small fixings for strength.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'drill', 'hints' => 'Tool for penetrating matter.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'model', 'hints' => 'Simplified representation.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'metal', 'hints' => 'Solid and conductive element.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'sugar', 'hints' => 'Sweet structural energy.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'robot', 'hints' => 'Automated helper machine.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'gizmo', 'hints' => 'Small engineered contraption.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'radar', 'hints' => 'Detects signals from afar.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'joint', 'hints' => 'Connects parts together.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'cages', 'hints' => 'Containment with structure.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'femur', 'hints' => 'Strong upper limb bone.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'tibia', 'hints' => 'Lower leg’s sturdy pillar.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'ulnar', 'hints' => 'Related to forearm structure.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'molar', 'hints' => 'Heavy duty dental component.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'clean', 'hints' => 'Purified state of matter.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'flask', 'hints' => 'Container for vital liquids.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'pipet', 'hints' => 'Delivers measured drops.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'vials', 'hints' => 'Small containers of essence.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'plate', 'hints' => 'Flat support structure.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'media', 'hints' => 'Cultivates life or data.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'glove', 'hints' => 'Protective covering in touch.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'array', 'hints' => 'Ordered collection of elements.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'crown', 'hints' => 'Topmost part in hierarchy.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'titan', 'hints' => 'Massive strength represented.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'fiber', 'hints' => 'Thread-like reinforcing element.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'sonar', 'hints' => 'Echoes to reveal hidden forms.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'biome', 'hints' => 'Ecosystem in miniature.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'wound', 'hints' => 'Scar from a delicate breach.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'hydro', 'hints' => 'Involving the flow of water.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'swell', 'hints' => 'Gradual increase in size.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'trace', 'hints' => 'Subtle mark left behind.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'sharp', 'hints' => 'Edges that cut through limits.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'tough', 'hints' => 'Resistant under pressure.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'stiff', 'hints' => 'Rigid in its form.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'rigid', 'hints' => 'Unyielding structure at heart.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'mould', 'hints' => 'Shape forming substance.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'medic', 'hints' => 'Healer in complex forms.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'album', 'hints' => 'Collection of structured memories.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'scalp', 'hints' => 'Surface layer of protection.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'mucus', 'hints' => 'Sticky natural secretion.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'blood', 'hints' => 'Life’s crimson river.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'clots', 'hints' => 'Aggregated defense in flow.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'blade', 'hints' => 'Cutting edge component.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'gauge', 'hints' => 'Measures the unknown.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'logic', 'hints' => 'System of reasoned design.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'synth', 'hints' => 'Artificially produced wave.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'trial', 'hints' => 'Test phase in development.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'study', 'hints' => 'Investigation into details.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'scale', 'hints' => 'Measures weight and proportion.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'glass', 'hints' => 'Transparent engineered material.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'anode', 'hints' => 'Attracts the charged companion.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'elect', 'hints' => 'Chooses with current intent.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'meter', 'hints' => 'Quantifies the unseen force.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'graph', 'hints' => 'Visual data storyteller.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'field', 'hints' => 'Area of influential power.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'force', 'hints' => 'Pushes or pulls with energy.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'sound', 'hints' => 'Vibration turned into sensation.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'spore', 'hints' => 'Tiny seed of potential.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'phage', 'hints' => 'Intruder of bacterial realms.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'virus', 'hints' => 'Microscopic invader in disguise.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'plasm', 'hints' => 'Gel-like base of many systems.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'shear', 'hints' => 'Cuts through resistance.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'cloth', 'hints' => 'Woven network of fibers.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'salve', 'hints' => 'Soothing remedy in action.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'sling', 'hints' => 'Supports with gentle hold.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'brace', 'hints' => 'Stabilizes in critical moments.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'strap', 'hints' => 'Ties components securely.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'bands', 'hints' => 'Groups in unison.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'nodes', 'hints' => 'Connecting points in a network.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'links', 'hints' => 'Bridges between components.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'pixel', 'hints' => 'Small unit of digital view.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'radii', 'hints' => 'Multiple measures from a center.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'spoke', 'hints' => 'Extends from a central hub.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'steel', 'hints' => 'Strong alloy element.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'rivet', 'hints' => 'Fastens with puncturing force.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'bolts', 'hints' => 'Quick fasteners in motion.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'wires', 'hints' => 'Conducts unseen energy.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'input', 'hints' => 'Entry point for signals.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'board', 'hints' => 'Flat surface for assembly.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'chips', 'hints' => 'Tiny fragments of creation.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'debug', 'hints' => 'Finds errors in the system.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'react', 'hints' => 'Responds to environmental cues.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'titer', 'hints' => 'Measures concentration subtly.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'doser', 'hints' => 'Dispenses in measured drops.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'doses', 'hints' => 'Portions for regulated effect.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'liver', 'hints' => 'Key filter of vital essence.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'lungs', 'hints' => 'Air-filled life exchangers.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'colon', 'hints' => 'Connector in the body.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'stoma', 'hints' => 'Opening to nature’s cycle.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'orbit', 'hints' => 'Encircles a central force.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'pupil', 'hints' => 'Opens to incoming insight.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'bicep', 'hints' => 'Strength found on the arm.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'chest', 'hints' => 'Houses the vital core.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'knees', 'hints' => 'Bend to support movement.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'ankle', 'hints' => 'Joint with pivoting motion.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'wrist', 'hints' => 'Connects with fluid motion.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'ulnae', 'hints' => 'Forearm’s supporting element.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'cheek', 'hints' => 'Soft layer on the surface.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'mouth', 'hints' => 'Entryway to nourishment.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'teeth', 'hints' => 'Grips with hard edges.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'gland', 'hints' => 'Produces secret essentials.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'sweat', 'hints' => 'Drips in stress relief.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'ceram', 'hints' => 'Engineered ceramic form.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'molds', 'hints' => 'Shaping substance in change.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'drone', 'hints' => 'Unmanned aerial presence.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'cyber', 'hints' => 'Digital realm embodiment.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'smart', 'hints' => 'Intelligence in design.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'touch', 'hints' => 'Felt but not seen.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'drive', 'hints' => 'Initiates a powerful motion.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'boost', 'hints' => 'Enhances an existing flow.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'amino', 'hints' => 'Basic block of creation.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'scope', 'hints' => 'Extends sight beyond limits.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'video', 'hints' => 'Moving picture capture.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'lumen', 'hints' => 'Inner brightness revealed.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'nexus', 'hints' => 'Central point of connection.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'align', 'hints' => 'Brings order to chaos.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'adapt', 'hints' => 'Adjusts to new conditions.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'torso', 'hints' => 'Central body structure.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'genes', 'hints' => 'Blueprint of life coded.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'genic', 'hints' => 'Pertaining to hereditary traits.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'beats', 'hints' => 'Rhythms that echo subtly.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'tempo', 'hints' => 'Speed measured in pulses.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'print', 'hints' => 'Transfers design onto form.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'curve', 'hints' => 'Subtle bend in structure.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'image', 'hints' => 'Visual imprint created.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'color', 'hints' => 'Shade of perception.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'shade', 'hints' => 'Subtle variation in light.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'layer', 'hints' => 'Strata of complex design.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'blend', 'hints' => 'Merges diverse elements.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'paste', 'hints' => 'Adheres without pressure.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'scabs', 'hints' => 'Marks of healing progress.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'drape', 'hints' => 'Folds with careful manner.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'gowns', 'hints' => 'Draped protective covering.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'masks', 'hints' => 'Veils of unseen defense.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'flesh', 'hints' => 'Soft tissue of form.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'clamp', 'hints' => 'Grips with firm pressure.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'serum', 'hints' => 'Concentrated healing agent.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'mucin', 'hints' => 'Sticky biological binder.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'braze', 'hints' => 'Fuses materials with hidden heat.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'lipid', 'hints' => 'Fatty cellular component.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'nylon', 'hints' => 'Synthetic and resilient fiber.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'spool', 'hints' => 'Coiled and ready to use.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'lever', 'hints' => 'Simple tool for leverage.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'pedal', 'hints' => 'Presses for kinetic input.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'track', 'hints' => 'Path laid for movement.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'wheel', 'hints' => 'Round carrier of motion.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'shift', 'hints' => 'Subtle change in position.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'relay', 'hints' => 'Passes the signal along.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'crimp', 'hints' => 'Creates a secure bond.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'yield', 'hints' => 'Gives way under pressure.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'error', 'hints' => 'Deviation from expected norm.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'sigma', 'hints' => 'Symbol of summation and limits.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'alpha', 'hints' => 'Beginning of a sequence.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'omega', 'hints' => 'Final note in a cycle.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'theta', 'hints' => 'Angle in ancient measure.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'delta', 'hints' => 'Change written in form.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'proof', 'hints' => 'Verifies with certainty.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'chart', 'hints' => 'Visual map of data.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'spins', 'hints' => 'Rotates in quiet motion.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'ionic', 'hints' => 'Charged with subtle influence.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'volts', 'hints' => 'Measures electric potential.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'fetal', 'hints' => 'Early stage of development.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'count', 'hints' => 'Keeps numerical track.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'split', 'hints' => 'Divides into separate parts.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'clone', 'hints' => 'Exact duplicate in design.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'mixes', 'hints' => 'Combines with creative force.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'photo', 'hints' => 'Captures light in form.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'mason', 'hints' => 'Crafts with enduring strength.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'visor', 'hints' => 'Shields from bright exposure.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'sight', 'hints' => 'Observation of subtle cues.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'oxide', 'hints' => 'Compound with oxygen touch.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'salts', 'hints' => 'Crystals that enhance function.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'seeds', 'hints' => 'Beginnings of growth concealed.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'build', 'hints' => 'Constructs with careful order.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'craft', 'hints' => 'Skillful creation in form.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'shape', 'hints' => 'Outline of intended design.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'lamin', 'hints' => 'Layered protection in design.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'stain', 'hints' => 'Marks that alter the surface.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'plugs', 'hints' => 'Stops a flow temporarily.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'cuffs', 'hints' => 'Edges that secure movement.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'bends', 'hints' => 'Curves in response to force.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'shaft', 'hints' => 'Central rod in rotation.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'swing', 'hints' => 'Moves with pendular grace.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'angle', 'hints' => 'Measures deviation in form.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'ratio', 'hints' => 'Relationship between parts.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'spasm', 'hints' => 'Sudden, brief contraction.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'cocci', 'hints' => 'Round shapes in biology.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'bacil', 'hints' => 'Bacterial shape in miniature.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'viral', 'hints' => 'Pertaining to microscopic invaders.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'tumor', 'hints' => 'Unexpected growth observed.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'hertz', 'hints' => 'Frequency measured in cycles.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'novel', 'hints' => 'Unique in its formulation.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'demos', 'hints' => 'Previews of working designs.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'codes', 'hints' => 'Encrypted instructions in play.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'setup', 'hints' => 'Arranges parts for function.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'derma', 'hints' => 'Skin-like protective layer.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'vapor', 'hints' => 'Gaseous state in transition.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'valve', 'hints' => 'Controls a vital flow.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'dials', 'hints' => 'Adjusts with measured precision.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'pumps', 'hints' => 'Drives movement in cycles.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'grasp', 'hints' => 'Holds with measured intent.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'solve', 'hints' => 'Unravels a complex puzzle.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'edges', 'hints' => 'Borders of defined structure.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'slice', 'hints' => 'Cuts with subtle finesse.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'stack', 'hints' => 'Arranges in ordered layers.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'scrub', 'hints' => 'Cleans with determined force.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'waste', 'hints' => 'Unused remnants in flux.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'disks', 'hints' => 'Flat rounds of compact form.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'ulcer', 'hints' => 'Surface breach in structure.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'sebum', 'hints' => 'Oily secretion on the surface.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'venom', 'hints' => 'Toxic essence in disguise.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'mimic', 'hints' => 'Imitates without full clarity.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'hinge', 'hints' => 'Pivot that connects movement.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'pivot', 'hints' => 'Central turning mechanism.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'traps', 'hints' => 'Catches in subtle restraint.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'delts', 'hints' => 'Shoulder muscles in action.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'glute', 'hints' => 'Buttock power in design.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'quads', 'hints' => 'Front thigh strength evident.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'calfs', 'hints' => 'Lower limbs in subtle motion.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'thyro', 'hints' => 'Hints at glandular regulation.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'ovary', 'hints' => 'Source of creative potential.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'ovule', 'hints' => 'Seed of future design.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'sperm', 'hints' => 'Carrier of genetic blueprint.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'myelo', 'hints' => 'Core tissue fueling growth.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'chord', 'hints' => 'Connects with underlying tone.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'floss', 'hints' => 'Thread used in delicate care.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'mixer', 'hints' => 'Combines elements into one.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'humid', 'hints' => 'Moisture in the air hinted.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'spray', 'hints' => 'Disperses in a fine mist.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'scoop', 'hints' => 'Lifts material with subtle force.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'spoon', 'hints' => 'Curved tool for gentle transfer.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'grind', 'hints' => 'Breaks down with persistent force.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'cache', 'hints' => 'Stores away for later use.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'digit', 'hints' => 'Numeral in a tiny form.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'class', 'hints' => 'Group with similar traits.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'table', 'hints' => 'Structured layout for data.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'blink', 'hints' => 'Brief light in a sequence.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'human', 'hints' => 'Represents life in complexity.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'acryl', 'hints' => 'Synthetic polymer in design.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'epoxy', 'hints' => 'Adhesive bonding in layers.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'gauze', 'hints' => 'Light fabric for protection.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'cover', 'hints' => 'Encloses with gentle care.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'visco', 'hints' => 'Sticky resistance observed.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'creep', 'hints' => 'Slow movement in silence.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'cycle', 'hints' => 'Repeating sequence in time.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'phase', 'hints' => 'Distinct stage in a process.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'rapid', 'hints' => 'Quick change in dynamics.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'spurt', 'hints' => 'Sudden burst in activity.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'dosed', 'hints' => 'Measured and controlled amount.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'tuned', 'hints' => 'Adjusted to fine balance.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'drift', 'hints' => 'Slow, meandering movement.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'crisp', 'hints' => 'Clear and well-defined edge.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'flock', 'hints' => 'Grouped in subtle unity.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'swarm', 'hints' => 'Mass in coordinated motion.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'brisk', 'hints' => 'Energetic and lively flow.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'vivid', 'hints' => 'Bright but not overt.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'shunt', 'hints' => 'Redirects with gentle force.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'drain', 'hints' => 'Draws away gradually.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'flush', 'hints' => 'Cleanses with a burst.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'bloat', 'hints' => 'Swells beyond normal bounds.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'pores', 'hints' => 'Microscopic openings present.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'order', 'hints' => 'System of organized parts.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'sieve', 'hints' => 'Filters with fine mesh.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'moist', 'hints' => 'Dampness lightly observed.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'pasty', 'hints' => 'Thick texture noted subtly.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'grant', 'hints' => 'Gives in measured portions.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'paper', 'hints' => 'Sheet material for display.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'stats', 'hints' => 'Numbers hinting at trends.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'histo', 'hints' => 'Study of tissue layers.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'fibro', 'hints' => 'Connective tissue element.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'myoid', 'hints' => 'Muscle-like characteristics.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'cough', 'hints' => 'Expels air with a burst.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'drugs', 'hints' => 'Medicinal compounds applied.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'pills', 'hints' => 'Small doses of remedy.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'nurse', 'hints' => 'Cares in a subtle manner.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'toxic', 'hints' => 'Harmful when uncontrolled.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'germs', 'hints' => 'Microscopic life forms abound.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'prion', 'hints' => 'Protein with mysterious traits.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'heals', 'hints' => 'Restores with quiet strength.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'dress', 'hints' => 'Covers with structured fabric.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'biont', 'hints' => 'Living unit in a system.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'shock', 'hints' => 'Sudden jolt of energy.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'brake', 'hints' => 'Slows down with resistance.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'smoke', 'hints' => 'Airborne mist not fully clear.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'glaze', 'hints' => 'Shiny surface in formation.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'agent', 'hints' => 'Acts with hidden intent.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'clear', 'hints' => 'Unclouded, yet not bare.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'blunt', 'hints' => 'Direct without sharpness.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'round', 'hints' => 'Curved and complete.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'focal', 'hints' => 'Center of subtle interest.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'sweep', 'hints' => 'Moves broadly without detail.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'forge', 'hints' => 'Heats and shapes with vigor.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'frame', 'hints' => 'Supports an underlying structure.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'light', 'hints' => 'Illuminates with gentle glow.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'focus', 'hints' => 'Centers attention subtly.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'welds', 'hints' => 'Fuses parts in quiet union.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'smock', 'hints' => 'Protects with a covering layer.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'fuses', 'hints' => 'Connects in a circuit of power.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'caput', 'hints' => 'Latin for head in design.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'steam', 'hints' => 'Vapor rising with energy.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'scent', 'hints' => 'Hint of fragrance in air.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'gamut', 'hints' => 'Range that spans subtlety.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'ducts', 'hints' => 'Channels guiding the flow.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'fossa', 'hints' => 'Depressed area in structure.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'sulci', 'hints' => 'Grooves marking complex surfaces.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'gyrus', 'hints' => 'Curved ridge in a network.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'mirna', 'hints' => 'Tiny regulator in life.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'assay', 'hints' => 'Tests with measured precision.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'recon', 'hints' => 'Surveying details discreetly.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'spike', 'hints' => 'Sudden rise in measurement.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'alert', 'hints' => 'Signals to take notice.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'prick', 'hints' => 'Tiny puncture in form.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'lance', 'hints' => 'Pierces with slender form.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'beads', 'hints' => 'Small rounded elements.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'smear', 'hints' => 'Spread with gentle touch.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'agile', 'hints' => 'Moves with nimble grace.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'dimer', 'hints' => 'Pair bonded in subtle form.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'latch', 'hints' => 'Secures with a simple catch.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'tacho', 'hints' => 'Measures rotations in time.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'press', 'hints' => 'Applies pressure with intent.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'filmy', 'hints' => 'Thin and translucent quality.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'flank', 'hints' => 'Side element of a structure.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'cramp', 'hints' => 'Sudden contraction observed.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'itchy', 'hints' => 'Subtle urge to scratch.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'swirl', 'hints' => 'Circular motion with grace.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'rinse', 'hints' => 'Cleans with flowing water.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'drips', 'hints' => 'Drops falling intermittently.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'drops', 'hints' => 'Falling beads of liquid.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'coapt', 'hints' => 'Joins parts with gentle touch.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'wheal', 'hints' => 'Raised mark not fully clear.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'fetus', 'hints' => 'Early form in development.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'niche', 'hints' => 'Small specialized area.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'singe', 'hints' => 'Light burn marks in form.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'scald', 'hints' => 'Heat that lightly burns.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'erode', 'hints' => 'Wears away over time.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0],
            ['term' => 'hepar', 'hints' => 'Hints at a vital, flowing source.', 'created_at' => $timestamp, 'updated_at' => $timestamp, 'viewed_count' => 0]
        ];
        DB::table('bmec_worlde_terms')->upsert($data, ['term']);
    }
}
